// Animation names
#define HANDSWEAPON_ANIM_DEFAULT 0
#define HANDSWEAPON_ANIM_IDLE 3
#define HANDSWEAPON_ANIM_ACTIVATE 1
#define HANDSWEAPON_ANIM_DEACTIVATE 2
#define HANDSWEAPON_ANIM_ATTACK 4

// Color names

// Patch names

// Names of collision boxes
#define HANDSWEAPON_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define HANDSWEAPON_ATTACHMENT_LEFT_01 0
#define HANDSWEAPON_ATTACHMENT_LEFT_02 1
#define HANDSWEAPON_ATTACHMENT_LEFT_03 2
#define HANDSWEAPON_ATTACHMENT_LEFT_04 3
#define HANDSWEAPON_ATTACHMENT_LEFT_05 4
#define HANDSWEAPON_ATTACHMENT_LEFT_06 5
#define HANDSWEAPON_ATTACHMENT_RIGHT_01 6
#define HANDSWEAPON_ATTACHMENT_RIGHT_02 7
#define HANDSWEAPON_ATTACHMENT_RIGHT_03 8
#define HANDSWEAPON_ATTACHMENT_RIGHT_04 9
#define HANDSWEAPON_ATTACHMENT_RIGHT_05 10
#define HANDSWEAPON_ATTACHMENT_RIGHT_06 11

// Sound names
