// Animation names
#define KNIFENEW_ANIM_DEFAULT 0
#define KNIFENEW_ANIM_HIDE 1
#define KNIFENEW_ANIM_SHOW 2
#define KNIFENEW_ANIM_IDLE 3
#define KNIFENEW_ANIM_THROWRIGHT 4
#define KNIFENEW_ANIM_THROWLEFT 5

// Color names

// Patch names

// Names of collision boxes
#define KNIFENEW_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define KNIFENEW_ATTACHMENT_LEFTHAND 0
#define KNIFENEW_ATTACHMENT_RIGHTHAND 1
#define KNIFENEW_ATTACHMENT_KNIFE_01 2
#define KNIFENEW_ATTACHMENT_KNIFE_02 3
#define KNIFENEW_ATTACHMENT_KNIFE_03 4
#define KNIFENEW_ATTACHMENT_KNIFE_04 5

// Sound names
