// Animation names
#define PLAYER_ANIM_DEFAULT 0
#define PLAYER_ANIM_STAND 1
#define PLAYER_ANIM_BACKPEDAL 2
#define PLAYER_ANIM_BACKPEDAL_RUN 3
#define PLAYER_ANIM_JUMP_START 4
#define PLAYER_ANIM_JUMP_END 5
#define PLAYER_ANIM_TURNLEFT 6
#define PLAYER_ANIM_TURNRIGHT 7
#define PLAYER_ANIM_RUN 8
#define PLAYER_ANIM_WALK 9
#define PLAYER_ANIM_CROUCH 10
#define PLAYER_ANIM_RISE 11
#define PLAYER_ANIM_CROUCH_IDLE 12
#define PLAYER_ANIM_CROUCH_TURNLEFT 13
#define PLAYER_ANIM_CROUCH_TURNRIGHT 14
#define PLAYER_ANIM_CROUCH_WALK 15
#define PLAYER_ANIM_CROUCH_WALKBACK 16
#define PLAYER_ANIM_SWIM 17
#define PLAYER_ANIM_SWIM_IDLE 18
#define PLAYER_ANIM_DEATH_UNDERWATER 19
#define PLAYER_ANIM_DEATH_UNDERWATERIDLE 20
#define PLAYER_ANIM_DEATH_BACK 21
#define PLAYER_ANIM_DEATH_BACKEASY 22
#define PLAYER_ANIM_DEATH_FORWARD 23
#define PLAYER_ANIM_DEATH_FORWARDEASY 24
#define PLAYER_ANIM_DEATH_SPIKES 25
#define PLAYER_ANIM_STATUE_PUT 26
#define PLAYER_ANIM_SPAWN_POSE 27
#define PLAYER_ANIM_BRIDGEFALLPOSE 28
#define PLAYER_ANIM_KEYLIFT 29
#define PLAYER_ANIM_ABYSSFALL 30
#define PLAYER_ANIM_SPAWN_FALLDOWN 31
#define PLAYER_ANIM_SPAWN_GETUP 32
#define PLAYER_ANIM_ENTERSPACESHIP 33
#define PLAYER_ANIM_INTRO 34
#define PLAYER_ANIM_IDLE_SERIOUSALEXEJ 35
#define PLAYER_ANIM_HIT_LEG 36
#define PLAYER_ANIM_HIT_LEG_FAST 37
#define PLAYER_ANIM_POSE_01 38
#define PLAYER_ANIM_POSE_02 39
#define PLAYER_ANIM_POSE_03 40
#define PLAYER_ANIM_POSE_04 41
#define PLAYER_ANIM_WRYYY_IN 42
#define PLAYER_ANIM_WRYYY_OUT 43

// Color names

// Patch names

// Names of collision boxes
#define PLAYER_COLLISION_BOX_STAND 0
#define PLAYER_COLLISION_BOX_CROUCH 1
#define PLAYER_COLLISION_BOX_SWIM 2
#define PLAYER_COLLISION_BOX_SWIMSMALL 3

// Attaching position names
#define PLAYER_ATTACHMENT_BODY 0
#define PLAYER_ATTACHMENT_NO_NAME 1

// Sound names
