// Animation names
#define ZAWARUDO_ANIM_DEFAULT 0
#define ZAWARUDO_ANIM_EMERGE 1
#define ZAWARUDO_ANIM_IDLE 2
#define ZAWARUDO_ANIM_ATTACKHANDS 3
#define ZAWARUDO_ANIM_ATTACKLEG 4
#define ZAWARUDO_ANIM_STOPTIME 5
#define ZAWARUDO_ANIM_DIE 6
#define ZAWARUDO_ANIM_THROW_KNIVES_1 7
#define ZAWARUDO_ANIM_THROW_KNIVES_2 8

// Color names

// Patch names

// Names of collision boxes
#define ZAWARUDO_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define ZAWARUDO_ATTACHMENT_RIGHTGHOST 0
#define ZAWARUDO_ATTACHMENT_LEFTGHOST 1
#define ZAWARUDO_ATTACHMENT_RIGHTLEGGHOST 2

// Sound names
