// Animation names
#define ZAWARUDO_ANIM_DEFAULT 0
#define ZAWARUDO_ANIM_EMERGE 1
#define ZAWARUDO_ANIM_IDLE 2
#define ZAWARUDO_ANIM_ATTACKHANDS 3
#define ZAWARUDO_ANIM_ATTACKLEG 4
#define ZAWARUDO_ANIM_STOPTIME 5
#define ZAWARUDO_ANIM_DIE 6
#define ZAWARUDO_ANIM_THROW_KNIVES_1 7
#define ZAWARUDO_ANIM_THROW_KNIVES_2 8
#define ZAWARUDO_ANIM_DEMO 9
#define ZAWARUDO_ANIM_DEMO0 10
#define ZAWARUDO_ANIM_DEMO2 11
#define ZAWARUDO_ANIM_HANDSFINALBLOW 12
#define ZAWARUDO_ANIM_LEGSFINALBLOW 13

// Color names

// Patch names

// Names of collision boxes
#define ZAWARUDO_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define ZAWARUDO_ATTACHMENT_RIGHT_1 0
#define ZAWARUDO_ATTACHMENT_LEFT_1 1
#define ZAWARUDO_ATTACHMENT_RIGHTLEG_1 2
#define ZAWARUDO_ATTACHMENT_RIGHT_2 3
#define ZAWARUDO_ATTACHMENT_RIGHT_3 4
#define ZAWARUDO_ATTACHMENT_LEFT_2 5
#define ZAWARUDO_ATTACHMENT_LEFT_3 6
#define ZAWARUDO_ATTACHMENT_RIGHTLEG_2 7
#define ZAWARUDO_ATTACHMENT_RIGHTLEG_3 8

// Sound names
